### ISSUE TITLE
logpoint not working after edit with nodejs agent

### ISSUE THREAD

**Issue by sunnyy02** [runsidekick/sidekick#29]
I tried the demo project https://github.com/boroskoyo/sidekick-nodejs-quickstart
Following the instruction, and can get tracepoint working, but logpoint seems very unstable.
After adding a logpoint, it only work occasionally.
Even a logpoint is working, if you edit it and change the log expression, the change won't be effective.
More info: the issue above occurs on Mac. I tried the same on windows, and the logpoint actually works on the demo project. 
Still have a small issue of refreshing the logpoint events in VSCode. I have to click on the logpoint to refresh the events. The refresh icon button doesn't work.

**Comment by hserefal** [comment]
Hello, we recently released a new version of broker . When I checked your case with demo project after release,  everything seems fine. I hope it works for you now. 

Notify us about your status please so that we can continue working on it or close issue.

**Comment by sunnyy02** [comment]
Thanks @boroskoyo  for your response. I tried the version 0.0.14. The same problem still exist: the logpoint doesn't reflect any change. I have to delete the existing logpoint and add a new one to show the change. Please note that it is a problem for Mac only. It works for windows.

**Comment by boroskoyo** [comment]
Alright, I see. Let me try it again and get back to you asap 👨‍💻

**Comment by boroskoyo** [comment]
Tested this issue with our agents' latest version. It seems to be fixed by now
