### ISSUE TITLE
Mismatched typing for nodejs agent

### ISSUE THREAD

**Issue by PhakornKiong** [runsidekick/sidekick#9]
While setting up the agent using code method in typescript, faced with this error.

![image](https://user-images.githubusercontent.com/30017432/186746388-0c3d52ac-5a2b-48d2-bcb9-261d00391a73.png)

In documentation page, it only mention that `apiKey` is required. 
https://docs.runsidekick.com/installation/installing-agents/node.js/installation

In the typing for the config `@runsidekick/sidekick-agent-nodejs/dist/config/ConfigNames.d.ts`
![image](https://user-images.githubusercontent.com/30017432/186746807-53d394a5-9c6c-4e5c-9654-35b3ce38e093.png)

That two variable should be made optional.

**Comment by bcaglayan** [comment]
Hello @PhakornKiong, 

Thank you for your notice, we will mark these two config as optional on next version and notify to you

**Comment by serkan-ozal** [comment]
Hi @PhakornKiong ,
It has been fixed with the new version (`0.0.12`) of Sidekick Node.js agent.
Thanks for reporting the issue.
